### PR TITLE
Fixed DOB formatting on PII and Confirm Screen on multiple browsers

### PR DESCRIPTION
**Pull request by KramerJeff**
Had to adjust some more of the DOB formatting to work across browsers. Date-FNS seems to have better cross browser support than the 'moment' library. I double checked submitting customers on Chrome and Firefox.

### CODE REVIEW

**Review by ksalmon — CHANGES_REQUESTED** [review]
@KramerJeff Could you please add a video of this working

**Comment by KramerJeff** [comment]
https://www.loom.com/share/811d555fb57149b6b8f38ccb3577a4ac

**Comment by KramerJeff** [comment]
@ksalmon updated with recordings

**Comment by ksalmon** [comment]
@KramerJeff Thanks for the quick turnaround!

**Review by ksalmon — APPROVED** [review]

**Pull request merged**
